import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path

# Page Configuration - Responsive Sidebar & Mobile First
st.set_page_config(
    page_title="Chandaria Field Performance Dashboard", 
    layout="wide",
    initial_sidebar_state="auto"
)

# Custom CSS for Mobile Styling & Fixing Datepicker Popovers
st.markdown("""
    <style>
    /* Prevent sidebar datepicker calendar popup from getting cut off */
    div[data-baseweb="popover"] {
        z-index: 999999 !important;
    }
    div[data-testid="stSidebar"] {
        overflow-y: auto !important;
    }
    
    /* MOBILE ADAPTATIONS (<768px) */
    @media (max-width: 768px) {
        [data-testid="stMetricValue"] {
            font-size: 1.5rem !important;
            font-weight: 700 !important;
        }
        [data-testid="stMetricLabel"] {
            font-size: 0.8rem !important;
        }
        .css-1r6slb0, [data-testid="column"] {
            width: 100% !important;
            flex: 1 1 100% !important;
        }
    }
    
    /* DESKTOP ENHANCEMENTS */
    @media (min-width: 769px) {
        [data-testid="stMetricValue"] {
            font-size: 2.2rem !important;
        }
    }
    </style>
""", unsafe_allow_html=True)

# Target Web_Output Directory (Generated by Merger.py for Streamlit)
BASE_DIR = Path(__file__).parent.resolve()
OUTPUT_DIR = BASE_DIR / "Web_Output"

@st.cache_data(ttl=60)
def load_data(report_name):
    file_path = OUTPUT_DIR / f"{report_name}_Master.csv"
    if file_path.exists():
        try:
            df = pd.read_csv(file_path, low_memory=False)
            if "Date" in df.columns:
                df["Date"] = pd.to_datetime(df["Date"], errors='coerce')
            return df
        except Exception as e:
            st.error(f"Error reading {file_path.name}: {e}")
            return pd.DataFrame()
    return pd.DataFrame()

# Helper Function to Clean Data, Tag Projects, and Compute OSA Flags
def prepare_availability_data(df):
    df = df.copy()
    
    # 1. Exclude Jackie
    if "Supervisor Name" in df.columns:
        df = df[~df["Supervisor Name"].astype(str).str.lower().str.strip().eq("jackie")]
        
    # 2. Tag IB Project vs Core
    brand_col = "Brand Name" if "Brand Name" in df.columns else ("Brand" if "Brand" in df.columns else None)
    if brand_col:
        is_ib = df[brand_col].astype(str).str.lower().str.strip().str.endswith("ib")
        df["Project"] = is_ib.map({True: "IB Project", False: "Core"})
    else:
        df["Project"] = "Core"

    # 3. Clean Gap Reason Column
    gap_col = "Gap Reason" if "Gap Reason" in df.columns else ("GapReason" if "GapReason" in df.columns else None)
    df["_clean_reason"] = df[gap_col].astype(str).str.lower().str.strip() if gap_col else ""

    # 4. Compute Base OSA Flag (1 if available/filled, 0 if gap/empty)
    sku_col = None
    possible_cols = ["Number of SKUs", "Number Of SKUs", "SKU Count", "Quantity", "Available"]
    for col in possible_cols:
        if col in df.columns:
            sku_col = col
            break
            
    if sku_col:
        numeric_series = pd.to_numeric(df[sku_col], errors='coerce').fillna(0)
        df["OSA_Flag"] = (numeric_series > 0).astype(int)
    else:
        if gap_col:
            df["OSA_Flag"] = df[gap_col].isna().astype(int) | df[gap_col].astype(str).str.strip().eq("").astype(int)
        else:
            df["OSA_Flag"] = 1
            
    return df

st.title("📊 Chandaria Field Performance Dashboard")

# Navigation Tabs
tab1, tab2, tab3, tab4 = st.tabs([
    "Availability Report", 
    "Coverage Report", 
    "Planogram Report", 
    "Share of Shelf Report"
])

# ---------------------------------------------------------
# TAB 1: AVAILABILITY REPORT (OSA SPECIFIC)
# ---------------------------------------------------------
with tab1:
    df_avail = load_data("Availability Report")
    
    if df_avail.empty:
        st.warning("No master data file found at: Web_Output/Availability Report_Master.csv")
    else:
        df_avail = prepare_availability_data(df_avail)
        
        # Sidebar Filters
        st.sidebar.markdown("### Filters (Availability)")
        filtered_df = df_avail.copy()
        
        # 1. Project Filter
        project_options = ["All Projects"] + sorted(list(filtered_df["Project"].unique()))
        selected_project = st.sidebar.selectbox("Select Project", project_options, key="avail_proj")
        if selected_project != "All Projects":
            filtered_df = filtered_df[filtered_df["Project"] == selected_project]

        # 2. Date Range Filter
        if "Date" in filtered_df.columns and not filtered_df["Date"].dropna().empty:
            min_date = filtered_df["Date"].min().date()
            max_date = filtered_df["Date"].max().date()
            
            date_range = st.sidebar.date_input(
                "Select Date Range",
                value=(min_date, max_date),
                min_value=min_date,
                max_value=max_date,
                key="avail_date_range"
            )
            
            if isinstance(date_range, tuple) and len(date_range) == 2:
                start_d, end_d = date_range
                filtered_df = filtered_df[
                    (filtered_df["Date"].dt.date >= start_d) & 
                    (filtered_df["Date"].dt.date <= end_d)
                ]

        # 3. Supervisor Filter
        if "Supervisor Name" in filtered_df.columns:
            sups = ["All Supervisors"] + sorted([str(s) for s in filtered_df["Supervisor Name"].dropna().unique()])
            selected_sup = st.sidebar.selectbox("Supervisor", sups, key="avail_sup")
            if selected_sup != "All Supervisors":
                filtered_df = filtered_df[filtered_df["Supervisor Name"].astype(str) == selected_sup]

        # 4. Merchandiser / Employee Name Filter
        merch_col = "Employee Name" if "Employee Name" in filtered_df.columns else ("Merchandiser Name" if "Merchandiser Name" in filtered_df.columns else None)
        selected_merch = "All Merchandisers"
        if merch_col:
            merchs = ["All Merchandisers"] + sorted([str(m) for m in filtered_df[merch_col].dropna().unique()])
            selected_merch = st.sidebar.selectbox("Merchandiser Name", merchs, key="avail_merch")
            if selected_merch != "All Merchandisers":
                filtered_df = filtered_df[filtered_df[merch_col].astype(str) == selected_merch]

        # 5. Store Account Filter
        if "Store Account" in filtered_df.columns:
            accs = ["All Accounts"] + sorted([str(a) for a in filtered_df["Store Account"].dropna().unique()])
            selected_acc = st.sidebar.selectbox("Store Account", accs, key="avail_acc")
            if selected_acc != "All Accounts":
                filtered_df = filtered_df[filtered_df["Store Account"].astype(str) == selected_acc]

        # EXEMPTIONS: Exclude 'SKU Not Listed' AND 'Customer Has Not Ordered'
        exemptions_mask = (
            filtered_df["_clean_reason"].str.contains("sku not list", na=False) | 
            filtered_df["_clean_reason"].str.contains("customer has not order", na=False)
        ) if "_clean_reason" in filtered_df.columns else pd.Series(False, index=filtered_df.index)

        osa_eval_df = filtered_df[~exemptions_mask]
        overall_osa = osa_eval_df["OSA_Flag"].mean() * 100 if not osa_eval_df.empty else 0
        
        # Overall Metrics Cards
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Overall Average OSA %", f"{overall_osa:.2f}%", help="Excludes 'SKU Not Listed' & 'Customer Has Not Ordered'")
        
        if "Store Name" in filtered_df.columns:
            col2.metric("Outlets Monitored", f"{filtered_df['Store Name'].nunique():,}")
            
        if "Category" in filtered_df.columns:
            col3.metric("Categories Monitored", f"{filtered_df['Category'].nunique():,}")
            
        gap_col = "Gap Reason" if "Gap Reason" in filtered_df.columns else ("GapReason" if "GapReason" in filtered_df.columns else None)
        if gap_col:
            valid_gaps_df = filtered_df[
                filtered_df[gap_col].notna() & 
                (filtered_df[gap_col].astype(str).str.strip() != "") & 
                (~exemptions_mask)
            ]
            top_reason = valid_gaps_df[gap_col].mode()
            top_val = top_reason[0] if not top_reason.empty else "None"
            col4.metric("Top Gap Cause", str(top_val))

        st.markdown("---")

        # Side-by-Side Columns for Desktop (Stack on Mobile)
        c1, c2 = st.columns(2)
        
        cat_col = "Category" if "Category" in filtered_df.columns else ("Brand Name" if "Brand Name" in filtered_df.columns else None)

        # Chart 1: Average OSA % by Category
        with c1:
            if cat_col and not osa_eval_df.empty:
                st.subheader(f"Average OSA % by {cat_col}")
                cat_osa = osa_eval_df.groupby(cat_col)["OSA_Flag"].mean().reset_index()
                cat_osa["OSA %"] = (cat_osa["OSA_Flag"] * 100).round(2)
                cat_osa = cat_osa.sort_values(by="OSA %", ascending=True)
                cat_osa["Label"] = cat_osa["OSA %"].astype(str) + "%"
                
                fig_cat = px.bar(
                    cat_osa, x="OSA %", y=cat_col, orientation='h', text="Label", color="OSA %",
                    color_continuous_scale="Blues"
                )
                fig_cat.update_traces(
                    textposition='inside', 
                    textfont=dict(size=13, color='white', family='Arial Black')
                )
                fig_cat.update_layout(xaxis_range=[0, 105], coloraxis_showscale=False)
                st.plotly_chart(fig_cat, width="stretch")

        # Chart 2: Average Gap Reasons Breakdown (%)
        with c2:
            if gap_col and not filtered_df.empty:
                st.subheader("Gap Reasons Breakdown (%)")
                
                gaps_df = filtered_df[
                    filtered_df[gap_col].notna() & 
                    (filtered_df[gap_col].astype(str).str.strip() != "") & 
                    (~exemptions_mask)
                ].copy()
                
                if not gaps_df.empty:
                    gap_summary = gaps_df[gap_col].value_counts().reset_index()
                    gap_summary.columns = [gap_col, "Count"]
                    
                    total_gaps = gap_summary["Count"].sum()
                    gap_summary["Contribution %"] = ((gap_summary["Count"] / total_gaps) * 100).round(2)
                    gap_summary = gap_summary.sort_values(by="Contribution %", ascending=True)
                    gap_summary["Label"] = gap_summary["Contribution %"].astype(str) + "%"
                    
                    fig_gap = px.bar(
                        gap_summary, 
                        x="Contribution %", 
                        y=gap_col, 
                        orientation='h', 
                        text="Label",
                        color="Contribution %",
                        color_continuous_scale="Reds"
                    )
                    fig_gap.update_traces(
                        textposition='inside', 
                        textfont=dict(size=12, color='white', family='Arial Black')
                    )
                    fig_gap.update_layout(xaxis_range=[0, 105], coloraxis_showscale=False)
                    st.plotly_chart(fig_gap, width="stretch")
                else:
                    st.info("No actionable gaps logged for the selected filter criteria.")

        st.markdown("---")

        # DYNAMIC TABLE VIEW
        if selected_merch != "All Merchandisers":
            st.subheader(f"📋 Outlets Visited by Merchandiser: {selected_merch}")
            group_cols = []
            if "Store Account" in filtered_df.columns: group_cols.append("Store Account")
            if "Store Name" in filtered_df.columns: group_cols.append("Store Name")
        else:
            st.subheader("📋 OSA % Performance by Account & Supervisor")
            group_cols = []
            if "Store Account" in filtered_df.columns: group_cols.append("Store Account")
            if "Supervisor Name" in filtered_df.columns: group_cols.append("Supervisor Name")
            if "Project" in filtered_df.columns: group_cols.append("Project")
        
        if group_cols and not filtered_df.empty:
            summary_table = osa_eval_df.groupby(group_cols).agg(
                Total_Audits=("OSA_Flag", "count"),
                Available_SKUs=("OSA_Flag", "sum"),
                OSA_Percentage=("OSA_Flag", lambda x: round(x.mean() * 100, 2))
            ).reset_index().rename(columns={"OSA_Percentage": "OSA %"})
            
            summary_table = summary_table.sort_values(by="OSA %", ascending=False)
            st.dataframe(summary_table, width="stretch")

# ---------------------------------------------------------
# TABS 2-4: OTHER REPORTS
# ---------------------------------------------------------
def render_generic_tab(report_title):
    df = load_data(report_title)
    if df.empty:
        st.warning(f"No master data file found at: Web_Output/{report_title}_Master.csv")
    else:
        if "Supervisor Name" in df.columns:
            df = df[~df["Supervisor Name"].astype(str).str.lower().str.strip().eq("jackie")]
        st.subheader(f"{report_title} Overview")
        st.dataframe(df, width="stretch")

with tab2:
    render_generic_tab("Coverage Report")

with tab3:
    render_generic_tab("Planogram Report")

with tab4:
    render_generic_tab("Share of Shelf Report")